## Download dataset from Kaggle

In [32]:
!kaggle datasets download -d prathampithalia/project -f orders.csv -p . --unzip

Dataset URL: https://www.kaggle.com/datasets/prathampithalia/project
License(s): unknown
Downloading orders.csv to .

  0%|          | 0.00/1.29M [00:00<?, ?B/s]
 78%|███████▊  | 1.00M/1.29M [00:16<00:04, 63.9kB/s]
100%|██████████| 1.29M/1.29M [00:17<00:00, 79.8kB/s]
100%|██████████| 1.29M/1.29M [00:17<00:00, 75.4kB/s]

### Read data from the file and handle null values

In [33]:
import pandas as pd
df = pd.read_csv('orders.csv',na_values=['Not Available', 'unknown'])
df['Ship Mode'].unique()

df.head()

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

### Rename columns names and make them lower case and replace space with underscore

In [34]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

### Drive new columns discount, sale price, sales and profit

In [35]:
df['discount']=df['list_price']*df['discount_percent']*.01
df['sale_price']=df['list_price']-df['discount']

df["sales"] = df["sale_price"] * df["quantity"]

df["profit"] = (df["sale_price"] - df["cost_price"]) * df["quantity"]

### Convert order date from object data type to datetime

In [36]:
df.dtypes
df['order_date']=pd.to_datetime(df['order_date'],format="%Y-%m-%d")

### Drop cost price, list price and discount percent columns

### SQL Connection

In [ ]:
import sqlalchemy as sal

engine = sal.create_engine("mysql+pymysql://root:<your_password>@localhost:3306/project")

conn = engine.connect()
print("Connected to MySQL!")

Connected to MySQL!

### Load the data into sql server using append option

In [38]:
df.to_sql('df_orders', con=conn, index=False, if_exists = 'append')

9994